### ISSUE TITLE
Cannot get resources

### ISSUE THREAD

**Issue by llafcode** [tvd-dataset/TheBigBangTheory#3]
Run this `python -m tvd.create metadata /tmp/ TheBigBangTheory` and get messages like this:

`ERROR:root:TheBigBangTheory.Season01.Episode04: failed to download "transcript_aligned".
  ERROR:root:cannot get transcript_aligned for episode TheBigBangTheory.Season01.Episode04`

For all episodes. 

I did exactly the same as written in the Notebook here: https://nbviewer.jupyter.org/github/tvd-dataset/TheBigBangTheory/blob/master/documentation.ipynb

Did I miss something?

**Comment by hbredin** [comment]
Closing as we discussed this over email.
